FrontendProject/Models/ErrorViewModel.cs
namespace FrontendProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FrontendProject/Models/ListModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace FrontendProject.Models
{
    public class ListModel
    {
        [HiddenInput]
        public int Id { get; set; }
        public required string Name { get; set; }
        public List<TaskModel> TaskModels { get; set; } = new List<TaskModel>();
    }
}

FrontendProject/Models/TaskModel.cs
using System.ComponentModel.DataAnnotations;
using FrontendProject.Repositories;

namespace FrontendProject.Models
{
    public class TaskModel
    {
        public int Id { get; set; }
        public required string Name { get; set; }
        public string? Description { get; set; }
        public int ListId { get; set; }
    }
}

FrontendProject/Controllers/ListsController.cs
using FrontendProject.Models;
using FrontendProject.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FrontendProject.Controllers
{
    public class ListsController : Controller
    {
        private readonly ILogger<ListsController> _logger;
        private readonly IListRepository listRepository;

        public ListsController(ILogger<ListsController> logger, IListRepository listRepository)
        {
            _logger = logger;
            this.listRepository = listRepository;
        }

        public async Task<IActionResult> Index()
        {
            var allLists = await listRepository.GetAllLists();
            return View(allLists);
        }

        [HttpPost]
        public async Task<IActionResult> NewList(string name)
        {
            await listRepository.CreateList(name);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> RemoveList(int Id)
        {
            await listRepository.DeleteList(Id);
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}   

FrontendProject/Controllers/TasksController.cs
using FrontendProject.Models;
using FrontendProject.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;

namespace FrontendProject.Controllers
{
    public class TasksController : Controller
    {
        private readonly ILogger<ListsController> _logger;
        private readonly ITaskRepository taskRepository;
        private readonly IListRepository listRepository;

        public TasksController(ILogger<ListsController> logger, ITaskRepository taskRepository,
            IListRepository listRepository)
        {
            _logger = logger;
            this.taskRepository = taskRepository;
            this.listRepository = listRepository;
        }

        public async Task<IActionResult> Index(int listId)
        {
            var list = await listRepository.GetPopulatedList(listId);
            return View(list);
        }

        [HttpPost]
        public async Task<IActionResult> NewTask(int listID, string name, string description)
        {
            var newTask = new TaskModel
            {
                Name = name,
                Description = description,
                ListId = listID
            };
            await taskRepository.CreateTask(newTask);
            return RedirectToAction("Index", new { listId = listID });
        }

        [HttpPost]
        public async Task<IActionResult> RemoveTask(int Id, int ListId)
        {
            await taskRepository.DeleteTask(Id);
            return RedirectToAction("Index", new { listId = ListId });
        }

        [HttpPost]
        public async Task<IActionResult> MoveTask(int Id, string name, int listId)
        {
            var lists = await listRepository.GetAllLists();
            var listToMoveTo = lists.FirstOrDefault(l => name.Trim().Equals(l.Name));
            if (listToMoveTo != null)
                await taskRepository.MoveTask(Id, listToMoveTo.Id);
            return RedirectToAction("Index", new { listId });
        }

        [HttpPost]
        public async Task<IActionResult> EditTask(TaskModel taskModel)
        {
            await taskRepository.UpdateTask(taskModel);
            return RedirectToAction("Index", new { listId = taskModel.ListId });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FrontendProject/Views/Lists/Index.cshtml
@model IEnumerable<FrontendProject.Models.ListModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="text-center">
    <table class="table table-striped">
        @{
            var rowCounter = 0;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Tasks" asp-action="Index" asp-route-listId="@item.Id">@item.Name</a>
                    
                </td>
                <td>
                    <form asp-controller="Lists" asp-action="RemoveList" method="post">
                        <input type="hidden" id="Id" name="Id" value="@item.Id">
                        <button asp-action="RemoveList" class="btn btn-primary">Delete</button>
                    </form>
                </td>
            </tr>
            rowCounter++;
        }
    </table>
    <form asp-controller="Lists" asp-action="NewList" method="post">
        <label for="fname">New List Name:</label><br>
        <input type="text" id="name" name="name"><br>
        <button asp-action="NewList" class="btn btn-primary">Submit</button>
    </form>
</div>

FrontendProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontendProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontendProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Lists" asp-action="Index">FrontendProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lists" asp-action="Index">Lists</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FrontendProject/Views/Tasks/Index.cshtml
@model FrontendProject.Models.ListModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="text-center">
    @Model.Name
    <table class="table table-striped">
        @{
            var rowCounter = 0;
        }
        @foreach (var item in Model.TaskModels)
        {
            <tr>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Description
                </td>

                <td>
                    <form asp-controller="Tasks" asp-action="EditTask" method="post">
                        <input type="hidden" id="EdidId" name="Id" value="@item.Id">
                        <input type="hidden" id="EditListId" name="ListId" value="@Model.Id">
                        <input type="text" id="editName" name="name" value="@item.Name"><br>
                        <textarea type="text" id="description" name="description">@item.Description</textarea><br>
                        <button asp-action="EditTask" class="btn btn-primary">Edit</button>
                    </form>
                </td>
                <td>
                    <form asp-controller="Tasks" asp-action="MoveTask" method="post">
                        <input type="hidden" id="MoveId" name="Id" value="@item.Id">
                        <input type="hidden" id="MoveListId" name="listId" value="@Model.Id">
                        <input type="text" id="editName" name="name" value="@Model.Name"><br>
                        <button asp-action="MoveTask" class="btn btn-primary">Move To List name</button>
                    </form>
                </td>
                <td>
                    <form asp-controller="Tasks" asp-action="RemoveTask" method="post">
                        <input type="hidden" id="RemoveId" name="Id" value="@item.Id">
                        <input type="hidden" id="RemoveListId" name="ListId" value="@Model.Id">
                        <button asp-action="RemoveTask" class="btn btn-primary">Delete</button>
                    </form>
                </td>
            </tr>
            rowCounter++;
        }
    </table>
    <form asp-controller="Tasks" asp-action="NewTask" method="post">
        <label for="name">New Task:</label><br>
        <input type="text" id="name" name="name">Name<br>
        <input type="hidden" id="listID" name="listID" value="@Model.Id">
        <textarea type="text" id="description" name="description">Description</textarea><br>
        <button asp-action="NewTask" class="btn btn-primary">Submit</button>
    </form>
</div>